export ZSH=/usr/share/oh-my-zsh
export ZSH_CACHE_DIR=~/.cache/oh-my-zsh

ZSH_THEME="lukerandall"
DISABLE_AUTO_UPDATE="true"

plugins=(
  git
  tmux
)

source $ZSH/oh-my-zsh.sh

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

export GPG_TTY
gpg-connect-agent updatestartuptty /bye > /dev/null
